### ISSUE TITLE
Add version badge

### ISSUE THREAD

**Issue by Hirse** [brackets-extension-badges/brackets-extension-badges.github.io#2]
Feature request:  
Could you use the available data to offer a "Latest Uploaded Version"-badge like this one for npm:
![image](https://user-images.githubusercontent.com/2564094/32693991-fa9e769c-c6e9-11e7-8888-e8d4989dce3c.png)

**Comment by bokub** [comment]
Great idea, will do that soon

**Comment by bokub** [comment]
Done !
